# traefik.toml
################################################################
# Global configuration
################################################################

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "thibault.friedrich@gmail.com"
storageFile = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true
onDemand = true

[[acme.domains]]
  main = "portainer.techmind.io"

# no web access provided
# [web]
# address = ":8080"
# [web.auth.basic]
#   users = ["pab:$apr1$2ZtdZCue$BHq00nxavh6EFmR9OFAfZ1"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "vanaheim.techmind.io"
watch = true
exposedbydefault = true


# https://docs.traefik.io/configuration/logs/

logLevel = "INFO"
[traefikLog]
  filePath = "/etc/traefik/logs/traefik.log"
  format   = "json"
[accessLog]
  filePath = "/etc/traefik/logs/access.log"
  format = "json"
